name: flutter_expense_tracker_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  dropdown_button2: ^2.1.3
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  get: null
  get_storage: ^2.1.1
  google_fonts: ^5.0.0
  image_picker:
  intl: ^0.17.0
  sqflite: ^2.2.8+4
  file: ^6.1.4
  fluttertoast: ^8.2.2
  pdf: ^3.10.4
  path_provider: ^2.0.15
  url_launcher: ^6.1.11
  percent_indicator: ^4.2.3
  progress_indicator: ^0.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/